version: "3"

services:
  video_downloader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - /app/opt/openvidu/recordings:/opt/openvidu/recordings
